[package]
name = "dog-tunnel2"
version = "0.1.0"
authors = ["vzex <vzex@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
